project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown
    - examples/auto-package

execute:
  freeze: auto
  echo: true

metadata-files:
  - api/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/
    numpy:
      url: https://numpy.org/doc/stable/
    pandas:
      url: https://pandas.pydata.org/docs/
    ipython:
      url: https://ipython.readthedocs.io/en/stable/
    matplotlib:
      url: https://matplotlib.org/stable/
    scipy:
      url: https://docs.scipy.org/doc/scipy/
    statsmodels:
      url: https://www.statsmodels.org/stable/

website:
  title: "iplot"
  page-navigation: true
  navbar:
    left:
      - href: api/
        text: Reference
    right:
      - icon: github
        href: https://github.com/munch-group/iplot/
  sidebar:
    - id: pages
      title: Get Started
      style: floating
      align: left
      contents:
        - pages/getting_started.qmd
        # - section: "Widgets"
        #   contents:
        #     - pages/seaborn.qmd            
        - section: "Examples"
          contents:
            - examples/example.ipynb            
            # - examples/widgets.ipynb            
        - section: "Library reference"
          contents:
            - api/index.qmd

lightbox: true

format:
  html:
    theme: cosmo
    css:
      - api/_styles-quartodoc.css
      - styles.css
    toc: true
    mermaid:
      theme: neutral

quartodoc:
  style: pkgdown
  dir: api
  package: iplot
  render_interlinks: true
  options:
    signature_name: full
  renderer:
    style: markdown
    table_style: description-list
  sidebar: "api/_sidebar.yml"
  css: "api/_styles-quartodoc.css"

  sections:
    - title: Some section
      desc: ""
      contents:
        - iplot
        - iplot_settings

